### ISSUE TITLE
App com o banco zerado

### ISSUE THREAD

**Issue by illison** [mpirescarvalho/TIVendas#1]
Quando acesso o app pela primeira vez com o banco zerado, não há possibilidade de prosseguir da tela de login, visto que não há suporte para uma senha padrão na qual eu possa acessar o sistema, e percebi que no código também não faz menção a isso. Com isso fico preso na tela de login.

**Comment by mpirescarvalho** [comment]
No SQLHelper, onde está sendo criado as tabelas, também é criado um usuário padrão: login: root, senha: root
